site_name: "DeFi Data Marketplace"
site_description: "Discover, Distribute & Download DeFi Data"
site_author: Nevermined
site_url: https://nevermined-io.github.io/defi-marketplace/

# Repository
repo_name: nevermined-io/defi-marketplace
repo_url: https://github.com/nevermined-io/defi-marketplace

# Copyright
copyright: "Copyright &copy; 2021 Nevermined"

theme:
  name: material
  language: en
  features:
    - toc.integrate
    # - navigation.expand
    # - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: defimkt

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en

extra_css:
  - stylesheets/extra.css
  
# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: textileio
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_captions


# Customization
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://discord.gg/GZju2qScKq

nav:
  - Home: index.md
  - How to use the Marketplace: using_marketplace.md
  - Wallet set up: payment.md
  - Supported reports: reports.md
  - Social:
    - Discord: https://discord.gg/GZju2qScKq

