name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      working-directory: ./client
      run: |
        npm i
    - name: Run linters
      working-directory: ./client
      run: npm run lint
    - name: Build
      working-directory: ./client
      run: npm run build
